//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winleafs.Wpf.Views.Options {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Winleafs.Wpf.Views.Options.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm.
        /// </summary>
        public static string Algorithm {
            get {
                return ResourceManager.GetString("Algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0}?.
        /// </summary>
        public static string AreYouSureDeviceDeletion {
            get {
                return ResourceManager.GetString("AreYouSureDeviceDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any button to close.
        /// </summary>
        public static string CloseInfoLabel {
            get {
                return ResourceManager.GetString("CloseInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to spotify.
        /// </summary>
        public static string ConnectToSpotify {
            get {
                return ResourceManager.GetString("ConnectToSpotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer.
        /// </summary>
        public static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect from Spotify.
        /// </summary>
        public static string DisconnectFromSpotify {
            get {
                return ResourceManager.GetString("DisconnectFromSpotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect successful. Do not forget to remove Winleafs from your application list in your Spotify account..
        /// </summary>
        public static string DisconnectSuccessful {
            get {
                return ResourceManager.GetString("DisconnectSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To retrieve your IP address.
        /// </summary>
        public static string IcanhazipExplanation {
            get {
                return ResourceManager.GetString("IcanhazipExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid value for latitude.
        /// </summary>
        public static string InvalidLatitude {
            get {
                return ResourceManager.GetString("InvalidLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid value for longitude.
        /// </summary>
        public static string InvalidLongitude {
            get {
                return ResourceManager.GetString("InvalidLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get your location based on your IP address.
        /// </summary>
        public static string IPAPIExplanation {
            get {
                return ResourceManager.GetString("IPAPIExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Changing the language requires a restart to be applied..
        /// </summary>
        public static string LanguageRestartNote {
            get {
                return ResourceManager.GetString("LanguageRestartNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving latitude and longitude.
        /// </summary>
        public static string LatLongReceiveError {
            get {
                return ResourceManager.GetString("LatLongReceiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected Location: {0}, {1}.
        /// </summary>
        public static string LocationDetected {
            get {
                return ResourceManager.GetString("LocationDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to system tray on close.
        /// </summary>
        public static string MinimizeToSystemTray {
            get {
                return ResourceManager.GetString("MinimizeToSystemTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given name is already taken.
        /// </summary>
        public static string NameTaken {
            get {
                return ResourceManager.GetString("NameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No color has been selected for the new effect.
        /// </summary>
        public static string NoColorSelected {
            get {
                return ResourceManager.GetString("NoColorSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no name provided for the new effect.
        /// </summary>
        public static string NoNameProvided {
            get {
                return ResourceManager.GetString("NoNameProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a color.
        /// </summary>
        public static string PickAColor {
            get {
                return ResourceManager.GetString("PickAColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process reset interval in seconds.
        /// </summary>
        public static string ProcessResetInterval {
            get {
                return ResourceManager.GetString("ProcessResetInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid value for process reset interval (a number larger than 0).
        /// </summary>
        public static string ProcessResetIntervalError {
            get {
                return ResourceManager.GetString("ProcessResetIntervalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen mirror.
        /// </summary>
        public static string ScreenMirror {
            get {
                return ResourceManager.GetString("ScreenMirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let ambilight control brightness.
        /// </summary>
        public static string ScreenMirrorControlBrightness {
            get {
                return ResourceManager.GetString("ScreenMirrorControlBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen mirror settings per device.
        /// </summary>
        public static string ScreenMirrorDeviceInfo {
            get {
                return ResourceManager.GetString("ScreenMirrorDeviceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen mirror monitor.
        /// </summary>
        public static string ScreenMirrorMonitor {
            get {
                return ResourceManager.GetString("ScreenMirrorMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen mirror refresh rate per second.
        /// </summary>
        public static string ScreenMirrorRefreshRatePerSecond {
            get {
                return ResourceManager.GetString("ScreenMirrorRefreshRatePerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: changing the screen mirror settings requires a restart of Winleafs.
        /// </summary>
        public static string ScreenMirrorResetMessage {
            get {
                return ResourceManager.GetString("ScreenMirrorResetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set location
        ///by IP Adress.
        /// </summary>
        public static string SetLocationByIp {
            get {
                return ResourceManager.GetString("SetLocationByIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to Spotify. Please try again. If this issue persists, try deleting Winleafs from the list of apps in your Spotify account..
        /// </summary>
        public static string SpotifyNotConnected {
            get {
                return ResourceManager.GetString("SpotifyNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error when trying to connect with Spotify. Please report to the developers..
        /// </summary>
        public static string SpotifyUnknownError {
            get {
                return ResourceManager.GetString("SpotifyUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start at Windows startup.
        /// </summary>
        public static string StartAtWindowsStartup {
            get {
                return ResourceManager.GetString("StartAtWindowsStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get sunrise and sunset times based on your location.
        /// </summary>
        public static string SunsetSunriseAPIExplanation {
            get {
                return ResourceManager.GetString("SunsetSunriseAPIExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong when updating the sunrise and sunset times.
        /// </summary>
        public static string SunsetSunriseError {
            get {
                return ResourceManager.GetString("SunsetSunriseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualize.
        /// </summary>
        public static string Visualize {
            get {
                return ResourceManager.GetString("Visualize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winleafs Options.
        /// </summary>
        public static string WinleafsOptions {
            get {
                return ResourceManager.GetString("WinleafsOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server URL.
        /// </summary>
        public static string WinleafsServerURL {
            get {
                return ResourceManager.GetString("WinleafsServerURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winleafs uses the following APIs.
        /// </summary>
        public static string WinleafsUsesAPIs {
            get {
                return ResourceManager.GetString("WinleafsUsesAPIs", resourceCulture);
            }
        }
    }
}
