//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winleafs.Wpf.Views.MainWindows {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Winleafs.Wpf.Views.MainWindows.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active device.
        /// </summary>
        public static string ActiveDevice {
            get {
                return ResourceManager.GetString("ActiveDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active effect.
        /// </summary>
        public static string ActiveEffect {
            get {
                return ResourceManager.GetString("ActiveEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add device.
        /// </summary>
        public static string AddDevice {
            get {
                return ResourceManager.GetString("AddDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness.
        /// </summary>
        public static string Brightness {
            get {
                return ResourceManager.GetString("Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete confirmation.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure? Removing {0} will also remove its schedules.
        /// </summary>
        public static string DeleteDeviceAreYouSure {
            get {
                return ResourceManager.GetString("DeleteDeviceAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this schedule?.
        /// </summary>
        public static string DeleteScheduleAreYouSure {
            get {
                return ResourceManager.GetString("DeleteScheduleAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device actions.
        /// </summary>
        public static string DeviceActions {
            get {
                return ResourceManager.GetString("DeviceActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        public static string GitHub {
            get {
                return ResourceManager.GetString("GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred during setting of manual control..
        /// </summary>
        public static string ManualControlError {
            get {
                return ResourceManager.GetString("ManualControlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most used effects.
        /// </summary>
        public static string MostUsedEffects {
            get {
                return ResourceManager.GetString("MostUsedEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing.
        /// </summary>
        public static string Nothing {
            get {
                return ResourceManager.GetString("Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override.
        /// </summary>
        public static string Override {
            get {
                return ResourceManager.GetString("Override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override schedule.
        /// </summary>
        public static string OverrideSchedule {
            get {
                return ResourceManager.GetString("OverrideSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage profile.
        /// </summary>
        public static string PercentageProfile {
            get {
                return ResourceManager.GetString("PercentageProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload effects.
        /// </summary>
        public static string ReloadEffects {
            get {
                return ResourceManager.GetString("ReloadEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to reload the effects.
        /// </summary>
        public static string ReloadFailed {
            get {
                return ResourceManager.GetString("ReloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effects have successfully been reloaded.
        /// </summary>
        public static string ReloadSuccessful {
            get {
                return ResourceManager.GetString("ReloadSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this device.
        /// </summary>
        public static string RemoveDevice {
            get {
                return ResourceManager.GetString("RemoveDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all settings.
        /// </summary>
        public static string ResetAllSettings {
            get {
                return ResourceManager.GetString("ResetAllSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules.
        /// </summary>
        public static string Schedules {
            get {
                return ResourceManager.GetString("Schedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop manual.
        /// </summary>
        public static string StopManual {
            get {
                return ResourceManager.GetString("StopManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop manual control.
        /// </summary>
        public static string StopManualControl {
            get {
                return ResourceManager.GetString("StopManualControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountering issues?
        ///Hover over me!.
        /// </summary>
        public static string Stuck {
            get {
                return ResourceManager.GetString("Stuck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winleafs.
        /// </summary>
        public static string Winleafs {
            get {
                return ResourceManager.GetString("Winleafs", resourceCulture);
            }
        }
    }
}
